---
name: dependencies check
on:
  push:
    branches: [ 'main' ]
  pull_request:
    types: ['opened', 'synchronize']
    paths:
      - '.github/**'
      - '**.go'
      - 'go.mod'
      - 'go.sum'

permissions:
  contents: read

jobs:
  depscheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v7
        with:
          go-version-file: go.mod
      - name: Check go.mod/go.sum are tidy
        run: |
          go mod tidy
          git diff --exit-code -- go.mod go.sum || \
            (echo; echo "Unexpected difference in go.mod/go.sum files. Run 'go mod tidy' command or revert any go.mod/go.sum changes and commit."; exit 1)
